# Generated by Django 5.0.6 on 2024-07-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_por_producto', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cantidad_en_stock', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('ventas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fecha_de_stock', models.DateField(auto_now_add=True)),
                ('ultima_venta_fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
