# Generated by Django 5.0.6 on 2024-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('categoria', models.CharField(choices=[('Hogar', 'Hogoar'), ('Electronicos', 'Electronicos'), ('Comida', 'Comida')], max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='inventario',
        ),
    ]
