# Generated by Django 5.0.6 on 2024-07-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_product_delete_inventario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
    ]
