# Generated by Django 5.0.6 on 2024-07-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_product_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
