# Generated by Django 5.0.6 on 2024-07-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('categoria', models.CharField(choices=[('Hogar', 'Hogar'), ('Electronicos', 'Electronicos'), ('Comida', 'Comida')], max_length=50, null=True)),
            ],
        ),
    ]
