# Generated by Django 5.0.6 on 2024-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventory_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombe', models.CharField(max_length=100)),
                ('costo_por_item', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cantidad_en_stock', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('ventas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('stock_fecha', models.DateField(auto_now_add=True)),
                ('ultima_venta_fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
